# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d50cea6a455f5e927801003bea71b0ce"
application_url = "https://para-cleaners-piece-albany.trycloudflare.com"
embedded = true
name = "Test Subscription"
handle = "test-subscription-24"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "treesateststore.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customer_redact"
  compliance_topics = [ "customers/data_request", "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "selling_plan_groups/create", "selling_plan_groups/update" ]
  uri = "/webhooks/selling_plan_groups/create_or_update"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_attempts/failure" ]
  uri = "/webhooks/subscription_billing_attempts/failure"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_attempts/success" ]
  uri = "/webhooks/subscription_billing_attempts/success"

  [[webhooks.subscriptions]]
  topics = [ "subscription_billing_cycles/skip" ]
  uri = "/webhooks/subscription_billing_cycles/skip"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/activate" ]
  uri = "/webhooks/subscription_contracts/activate"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/cancel" ]
  uri = "/webhooks/subscription_contracts/cancel"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/create" ]
  uri = "/webhooks/subscription_contracts/create"

  [[webhooks.subscriptions]]
  topics = [ "subscription_contracts/pause" ]
  uri = "/webhooks/subscription_contracts/pause"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders,customer_write_customers,customer_write_own_subscription_contracts,read_all_orders,read_locales,read_locations,read_themes,read_customer_payment_methods,write_customers,write_metaobject_definitions,write_metaobjects,write_orders,write_products,write_translations,write_own_subscription_contracts"

[auth]
redirect_urls = [
  "https://para-cleaners-piece-albany.trycloudflare.com/auth/callback",
  "https://para-cleaners-piece-albany.trycloudflare.com/auth/shopify/callback",
  "https://para-cleaners-piece-albany.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
